# Generated by Django 3.2.9 on 2021-11-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200, verbose_name='Movie Details')),
                ('likes', models.IntegerField(null=True)),
                ('watch_count', models.IntegerField(default=0, null=True)),
                ('rate', models.PositiveIntegerField(default=0, null=True)),
                ('production_date', models.DateTimeField(null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
