# Generated by Django 3.2.9 on 2021-11-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Movie Description'),
        ),
    ]
