# Generated by Django 3.2.9 on 2021-11-07 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20211107_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='production_date',
        ),
    ]
